
local string_format = string.format
function printlog_table(text, node, ...)
    
    text = string_format(text, ...)
    printf("NPCD | %s | \n" .. utils_data.print_table(node, text, true), time_global(), ...)
end

function tablelength(T)
  if not T then return 0 end 
  local count = 0
  for _ in pairs(T) do count = count + 1 end
  return count
end

function copy(obj, seen)
  if type(obj) ~= 'table' then return obj end
  if seen and seen[obj] then return seen[obj] end
  local s = seen or {}
  local res = setmetatable({}, getmetatable(obj))
  s[obj] = res
  for k, v in pairs(obj) do res[copy(k, s)] = copy(v, s) end
  return res
end

-- Shuffle function using Fisher-Yates algorithm
function shuffle(tbl)
	for i = #tbl, 2, -1 do
		local j = math.random(i)
		tbl[i], tbl[j] = tbl[j], tbl[i]
	end
end

function get_npc_obj(npc_id)
	-- local npc_storage = db.storage[npc_id] and db.storage[npc_id].object
	-- local npc_level = npc_id and level.object_by_id(npc_id)
	-- printf("npc_id %s - by storage %s, by level %s", npc_id, npc_storage and npc_storage:id(), npc_level and npc_level:id())
	return npc_id and level.object_by_id(npc_id)
end

function get_desc_rank(npc_id)
	local npc = get_npc_obj(npc_id)
	return npc and ranks.get_se_obj_rank_name(npc) or ""
end

function get_npc_rank(npc)
	if type(npc.id) == "function" then
		return npc:character_rank()
	else
		local npc_data = utils_stpk.get_stalker_data(npc)
		return npc:rank()
	end
end

function get_npc_reputation(npc)
	if type(npc.id) == "function" then
		return npc:character_reputation()
	else
		return npc:reputation()
	end
end

local RANK = {
	novice = 1,
	trainee = 1,
	experienced = 2,
	professional = 2,
	veteran = 3,
	expert = 3,
	master = 4,
	legend = 5,
}

local RANK_DESC = {
	[1] = "I",
	[2] = "II",
	[3] = "III",
	[4] = "IV",
	[5] = "V",
}

-- this should come from EXP framework
function get_perk_rank(npc_id, perk_id)
	local npc = get_npc_obj(npc_id)
	local rank = "novice"
	if npc and npc:alive() then
		rank = ranks.get_se_obj_rank_name(npc)
	end

	return rank and RANK[rank] or 1
end

function get_perk_rank_desc(npc_id, perk_id)
	local rank = get_perk_rank(npc_id, perk_id)
	return RANK_DESC[rank]
end

function compute_diff(newclist, currentclist)

	if not currentclist then
		return newclist, {}
	end

	-- Convert currentclist to a set
	local current_set = {}
	for _, id in ipairs(currentclist) do
		current_set[id] = true
	end

	-- Convert newclist to a set
	local new_set = {}
	for _, id in ipairs(newclist) do
		new_set[id] = true
	end

	-- Find added IDs
	local added_ids = {}
	for _, id in ipairs(newclist) do
		if not current_set[id] then
			table.insert(added_ids, id)
		end
	end

	-- Find removed IDs
	local removed_ids = {}
	for _, id in ipairs(currentclist) do
		if not new_set[id] then
			table.insert(removed_ids, id)
		end
	end

	return added_ids, removed_ids
end

function is_rifle(weapon)
	if not weapon then return false end
	local sec = weapon:section()
    return sec and SYS_GetParam(0,sec,"kind", "na") == "w_rifle"
end


-- taken from Catspaw
function int_to_rgba(i)
	-- Converts integer to RGB or RGBA values
	-- returns r, g, b, a, defaulting alpha to 255 if not specified (value is <= 0xffffff)
	-- Improved bitwise version from RavenAscendant
	-- Should be functionally identical but much more efficient
	if not (i and type(i) == "number") then return end
	local a
	if i <= 0xffffff then a = 255 end
	return 	bit.band(bit.rshift(i, 16), 255),
			bit.band(bit.rshift(i, 8), 255),
			bit.band(i, 255),
			a or bit.band(bit.rshift(i, 24), 255)
--[[
	if not (i and type(i) == "number") then return end
	return 	floor(floor(i / 256) / 256) % 256, 
			floor(i / 256) % 256, 
			(i % 256), 
			(i > 0xffffff) and (floor(floor(floor(i / 256) / 256) / 256) % 256) or 255
--]]
end

function get_ui_element_color(ele)
	local ele = element_name and self[element_name]
	norm_alpha = norm_alpha or 1
	if ele then
		local base_a = clamp(tonumber(ele.basecolor and ele.basecolor.a) or 255, 0, 255)
		local alpha = (base_a * norm_alpha)
		local c = {}
		if ele.GetTextureColor then
			local i = ele:GetTextureColor()
			c.r,c.g,c.b,c.a = i and int_to_rgba(i)
			-- c.a = alpha or c.a
			return c
		end
		-- if text_also then
		-- 	c = ele.currcolor or ele.basecolor or {}
		-- 	c.a = alpha or c.a
		-- 	c.r = c.r or 255
		-- 	c.g = c.g or 255
		-- 	c.b = c.b or 255
		-- 	ele.currcolor = c
		-- 	ele:TextControl():SetTextColor(get_argb(c.a,c.r,c.g,c.b))
		-- end
	end
end

function format_npc_time(npc_time)
	if not npc_time then return "" end
	local Y, M, D, h, m, s, ms = npc_time:get()
	return string.format("%04d-%02d-%02d %02d:%02d:%02d", Y, M, D, h, m, s)
end            