local npcdu = npcd_utils

function get_printer()
	if not Printer then
		Printer = npcd_logging.get_printer("npcd_ui_fx")
	end 
	LOG = Printer:GetLogTypes()
	CAT = Printer:GetLogCategories()
end
RegisterScriptCallback("npcd_on_log_update", get_printer)

Runner ={
    showing = {
        name = "showing",
        module = "npe_dialog_codec",
		group_name = "codec_ui",
		execution = npe_execution.TYPE.CONDITIONAL,
		stop_condition = { "npe_dialog_codec", "portrait_showing_completed", "actor" },
        start_timer = 0.15,
        loop_timer = 0.0,        
        functor = { "npe_dialog_codec", "show_portrait", "actor" },
		start = { "npe_dialog_codec", "on_start_show_portrait", "actor" },
		stop = { "npe_dialog_codec", "on_stop_show_portrait", "actor" },
    },	
    hiding = {
        name = "hiding",
        module = "npe_dialog_codec",
		group_name = "codec_ui",
		execution = npe_execution.TYPE.CONDITIONAL,
		stop_condition = { "npe_dialog_codec", "portrait_hiding_completed", "caller" },
        start_timer = 0.6,
        loop_timer = 0.0,      
        functor = { "npe_dialog_codec", "hide_portrait", "caller" },
		start = { "npe_dialog_codec", "on_start_hide_portrait", "caller" },
		stop = { "npe_dialog_codec", "on_stop_hide_portrait", "caller" },
    },		
	wide_scanlines = {
		name = "wide_scanlines",
		module = "npe_dialog_codec",
		group_name = "codec_ui",
		execution = npe_execution.TYPE.INFINITE,
		start_timer = 0.5,
		loop_timer = 0.04,
		functor = { "npe_dialog_codec", "run_portrait_wide_scanlines" },
		start = { "npe_dialog_codec", "on_start_portrait_wide_scanlines" },
	},
	scanlines = {
		name = "scanlines",
		module = "npcd_ui_fx",
		group_name = "npcd_ui_fx",
		execution = npe_execution.TYPE.INFINITE,
		start_timer = 0.1,
		loop_timer = 0.04,
		functor = { "npcd_ui_fx", "scanlines" },
		start = { "npcd_ui_fx", "on_start_scanlines" },
	},
    flickering = {
        name = "flickering",
        module = "npcd_ui_fx",
		group_name = "npcd_ui_fx",
		execution = npe_execution.TYPE.CONDITIONAL,
		stop_condition = { "npcd_ui_fx", "flickering_duration_ended" },
        start_timer = 0.015,
        loop_timer = 0.015,
        functor = { "npcd_ui_fx", "run_flickering" },
		start = { "npcd_ui_fx", "on_start_flickering" },
		stop = { "npcd_ui_fx", "on_stop_flickering" },
    },
    flickering_manager = {
        name = "flickering_manager",
		module = "npcd_ui_fx",
		group_name = "npcd_ui_fx",
		execution = npe_execution.TYPE.INFINITE,
        start_timer = 1,
        loop_timer = 1,
        functor = { "npcd_ui_fx", "run_flickering_manager" },
		start = { "npcd_ui_fx", "on_start_flickering_manager" },
		stop = { "npcd_ui_fx", "on_stop_flickering_manager" },
    },
}

FX = {
	SHOWING = "showing",
	HIDING = "hiding",
	FLICKERING_MANAGER = "flickering_manager",
	WIDE_SCANLINES = "wide_scanlines",
	SCANLINES = "scanlines",
	FLICKERING = "flickering",
}

local FX_CONFIG = {
	[FX.SHOWING] = {
	},
	[FX.HIDING] = {
	},
	[FX.WIDE_SCANLINES] = {
	},
	[FX.SCANLINES] = {
		type = FX.SCANLINES,
		dialog = nil,
		start = nil,
		speed = nil,
		orientation = 1, -- 0 - horizontal, 1 - vertical
		argb = {150, 255, 255, 255},
		margin_v = 0,
		margin_h = 0,
		direction = 1, -- 1 - in, -1 - out
		start_x = nil,
		start_y = nil,
		fx_ui = nil,
		fx_element = "scanline",
		init_on_start = false,
	},
	[FX.FLICKERING] = {
		type = FX.FLICKERING,
		dialog = nil,
		flickering_duration = nil,
		random_duration = false,
		flickering_cooldown = nil,
		random_cooldown = false,
		cooldown_value = 0,
		intensity = nil,
		speed = nil,
		fx_ui = nil,
		fx_element = nil,
		init_on_start = false,
	},
	[FX.FLICKERING_MANAGER] = {
		type = FX.FLICKERING_MANAGER,
		manager_type = FX.FLICKERING,
	},
}

local Managed = {
	[FX.FLICKERING] = {
	},
}

local FX_CONTROLS = {
	[FX.SCANLINES] = {
		direction = true
	}
}

local FX_JOBS = {
}

local xml = CScriptXmlInit()
xml:ParseFile("ui_npcd_fx.xml")

function get_fx_config(fx_name)
	return npcdu.copy(FX_CONFIG[fx_name])
end

function add_fx(fx_config)
	if not fx_config.type then
		Printer:Debug(LOG.ERROR, CAT.UI_ACTION," FX type not specified!")
		return
	end
	local fx_id = fx_config.type .. "_" .. tostring(math.random(10000, 99999))
	local new_runner = npcdu.copy(Runner[fx_config.type])
	new_runner.name = fx_id
	new_runner.start_timer = fx_config.start or new_runner.start_timer
	new_runner.loop_timer = fx_config.speed or new_runner.loop_timer
	FX_JOBS[fx_id] = {
		runner_name = fx_id,
		config = fx_config,
	}
	npe_execution.Add(new_runner)
	fx_config.id = fx_id
	if fx_config.fx_element and not fx_config.init_on_start then
		fx_config.fx_ui = xml:InitStatic(fx_config.fx_element, fx_config.dialog)
	end
	Printer:DebugTable("Adding FX:", fx_config)
end

function remove_fx(fx_id)
	local fx_job = FX_JOBS[fx_id]
	if fx_job then
		npe_execution.Remove(fx_job.runner_name)
		FX_JOBS[fx_id] = nil
	end
end

function stop_fx(fx_id)
	local fx_job = FX_JOBS[fx_id]
	if fx_job then
		npe_execution.Stop(fx_job.runner_name)
		FX_JOBS[fx_id] = nil
	end
end

function resume_fx(fx_id)
	local fx_job = FX_JOBS[fx_id]
	if fx_job then
		npe_execution.Resume(fx_job.runner_name)
	end
end

function update_fx(fx_id, name, value)
	local fx_job = FX_JOBS[fx_id]
	if not fx_job then return end
	if not FX_CONTROLS[fx_job.config.type][name] then return end

	fx_job.config[name] = value
end

function add_fx_to_manager(fx_id, manager_id)
	if not FX_JOBS[manager_id] then return end
	if not FX_JOBS[fx_id] then return end
	Printer:DebugTable("Adding FX to Manager:", {fx_id = fx_id, manager_id = manager_id})
	local manager = FX_JOBS[manager_id].config
	local manager_type = manager.manager_type
	if not Managed[manager_type] then
		Managed[manager_type] = {}
	end
	Managed[manager_type][fx_id] = fx_id
end

function remove_fx_from_manager(fx_id, manager_id)
	if not FX_JOBS[manager_id] then return end
	local manager = FX_JOBS[manager_id].config
	local manager_type = manager.manager_type
	if not Managed[manager_type] then return end
	Managed[manager_type][fx_id] = nil
end

function purge_fx_manager(manager_id)
	if not FX_JOBS[manager_id] then return end
	local manager = FX_JOBS[manager_id].config
	local manager_type = manager.manager_type
	if not Managed[manager_type] then return end
	Managed[manager_type] = {}
end

-- FX HANDLERS: SCANLINES

function scanlines(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config
	Printer:Debug(LOG.INFO, CAT.UI_ACTION," update scanlines %s", runner_name)
    local GUI = config.fx_ui
	if not GUI then return false end

	local y = GUI:GetWndPos().y
	local x = GUI:GetWndPos().x
	-- update scanlines
	if orientation == 0 then
		x = x + config.direction
		if x > config.ending_x then x = config.starting_x end
		if x < config.starting_x then x = config.ending_x end
	else 
		y = y + config.direction
		if y > config.ending_y then y = config.starting_y end
		if y < config.starting_y then y = config.ending_y end
	end
	GUI:SetWndPos(vector2():set(x, y))
	return true
end

function on_start_scanlines(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config
	if not config.dialog then return end
	Printer:Debug(LOG.INFO, CAT.UI_ACTION," on_start_scanlines %s", runner_name)

	config.starting_y = config.margin_v
	config.ending_y = config.dialog:GetHeight() - config.margin_v

	if config.init_on_start then
		config.fx_ui = xml:InitStatic(config.fx_element, config.dialog)
	end
	-- config.scanline:SetColor(GetARGB(config.argb[1], config.argb[2], config.argb[3], config.argb[4]))
	config.fx_ui:SetWndPos(vector2():set(config.margin_h, config.starting_y))
    config.fx_ui:SetWndSize(vector2():set(config.dialog:GetWidth() - (config.margin_h + config.margin_h / 2), config.fx_ui:GetHeight()))
	Printer:DebugTable("Scanline Config:", config)
	return true
end

-- FX HANDLERS: FLICKERING
local DEFAULT_ALPHA = 220
local FLICKERING_ALPHA = 180
local clr_cache = {}

local function change_alpha(clr, a)
    if not (clr and a ) then return end

    if not clr_cache[clr .. "_" .. a] then
        b = bit.band(clr, 255)
        g = bit.band(bit.rshift(clr, 8), 255)
        r = bit.band(bit.rshift(clr, 16), 255)
        clr_cache[clr .. "_" .. a] = GetARGB(a, r, g, b)
    end

    return clr_cache[clr .. "_" .. a]
end

function change_ui_alpha(ui_element, a)
	if not ui_element then return end
	local clr = ui_element:GetTextureColor()
	change_alpha(clr, a)
	ui_element:SetTextureColor(clr_cache[clr .. "_" .. a])
end

function run_flickering(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config
	Printer:Debug(LOG.INFO, CAT.UI_ACTION," running caller_flickering loop for %s", runner_name)
	-- flickering effect is done alternating alpha value of the ui element and switching its visibility
	if config.fx_ui:IsShown() then
		config.fx_ui:Show(false)
	else
		config.fx_ui:Show(true)
	end
end

function on_start_flickering(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config
	if not config.dialog then return end
	Printer:Debug(LOG.START, CAT.UI_ACTION," starting caller_flickering loop for %s", runner_name)

	-- the fx element is the original dialog manipulation
	config.fx_ui = config.dialog
	-- starting the flickering effect by setting duration and new alpha
	-- duration can be preset in config or calculated here
	config.flickering_duration = config.flickering_duration or (time_global() + math.random(10, 50) * 5)
	if config.random_duration then
		-- execute custom random duration functor
		local duration = execute_func(unpack(config.random_duration))
		if duration and type(duration) == "number" then
			config.flickering_duration = duration
		end
	end
	change_ui_alpha(config.fx_ui, FLICKERING_ALPHA)
	-- signal successful execution of start functor
	return true
end

function on_stop_flickering(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config
	if not config.fx_ui then return end
	Printer:Debug(LOG.STOP, CAT.UI_ACTION," stopping caller_flickering loop for %s", runner_name)

	-- ending the flickering effect by restoring default alpha and visibility, also setting cooldown for a flickering manager if used
	change_ui_alpha(config.fx_ui, DEFAULT_ALPHA)
	config.fx_ui:Show(true)
	config.flickering_duration = nil

	-- used when flickering is managed by a flickering manager
	config.cooldown_value = config.flickering_cooldown or (time_global() + math.random(10, 50) * 100)
	if config.random_cooldown then
		-- execute custom random cooldown functor
		local cooldown = execute_func(unpack(config.random_cooldown))
		if cooldown and type(cooldown) == "number" then
			config.cooldown_value = time_global() + cooldown
		end
	end
	-- signal successful execution of stop functor
	return true
end

function flickering_duration_ended(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config

	-- called by the npe execution to check if the flickering duration has ended
	if time_global() > config.flickering_duration then
		return true
	else
		return false
	end
end

-- FX HANDLERS: FLICKERING MANAGER

local current_level = 6

local function get_flicker_chance()
	local chance = math.random(1, 100)
	if current_level < 7 then
		chance = chance + (7 - current_level) * 10
	elseif current_level == 9 then
		chance = chance - 50
	end
	return chance
end

function run_flickering_manager(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	Printer:Debug(LOG.INFO, CAT.UI_ACTION," running flickering manager %s", runner_name)
	for _, managed_id in pairs(	Managed[FX.FLICKERING]) do
		local managed_config = FX_JOBS[managed_id]
		if not managed_config then return false end
		Printer:DebugTable("Flickering Manager checking managed fx:", managed_config)
		
		-- cannot run if scanline loop is active or it has a cooldown
		if managed_config.cooldown_value == 0 and not npe_execution.IsRunnerRunning(managed_config.runner_name) then
			-- start caller scanlines loop by chance			
			local flicker_chance = get_flicker_chance()
			if flicker_chance > 70 then
				npe_execution.Resume(managed_config.runner_name)
			end
		else
			if time_global() > managed_config.cooldown_value then
				managed_config.cooldown_value = 0
			end
		end
	end
end

function on_stop_flickering_manager(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	local config = fx_job.config
	if not config.dialog then return end
	for _, managed_id in pairs(	Managed[FX.FLICKERING]) do
		local managed_config = FX_JOBS[managed_id]
		if not managed_config then return false end
		-- stop caller flickering loop
		npe_execution.Stop(managed_config.runner_name)
	end
	return true
end

function on_start_flickering_manager(runner_name)
	local fx_job = FX_JOBS[runner_name]
	if not fx_job then return false end
	Printer:Debug(LOG.START, CAT.UI_ACTION," starting flickering manager %s", runner_name)
	for _, managed_id in pairs(	Managed[FX.FLICKERING]) do
		local managed_config = FX_JOBS[managed_id]
		if not managed_config then return false end
		-- initialize flickering cooldown
		managed_config.cooldown_value = 0
	end
	return true
end