local npcdu = npcd_utils

function get_printer()
	if not Printer then
		Printer = npcd_logging.get_printer("npcd_pda_dashboard")
	end 
	LOG = Printer:GetLogTypes()
	CAT = Printer:GetLogCategories()
end
RegisterScriptCallback("npcd_on_log_update", get_printer)


if not mac_mcm then
    local original_set_active_subdialog = pda.set_active_subdialog
    pda.set_active_subdialog = function (section)
        if (section == "eptNPCD") then
            return get_ui()
        else
            return original_set_active_subdialog(section)
        end
    end
end


local xml = CScriptXmlInit()

local SINGLETON = nil
function get_ui()
	SINGLETON = SINGLETON or npcd_dashboard_tab()
	return SINGLETON
end

-- APP
local APP = {
    HOME = "home",
    NPCS = "npcs",
    PERKS = "perks",
    DECK = "deck"
}

local UI_APP = {}
UI_APP = {
    [APP.HOME] = {
        active = nil,
        dialog = nil,
    },
    [APP.NPCS] = {
        active = nil,
        dialog = nil,
    },
    [APP.PERKS] = {
        active = nil,
        dialog = nil,
    },
    [APP.DECK] = {
        active = nil,
        dialog = nil,
    },
}
-- NPCS menu
local UI_MENU = {}
UI_MENU["npcs"] = {
    SQUAD = {},
    FAVORITES = {},
    RECRUITABLE = {},
    ALL = {},
    DEAD = {},
}

-- Perks menu
UI_MENU["perks"] = {
    DISCOVERED = {},
    ALL = {},
    LEARNED = {}
}

-- Deck menu
UI_MENU["deck"] = {
    PERKS = {},
    FEATS = {},
    EFFECTS = {}
}

-- Constructor.
class "npcd_dashboard_tab" (CUIScriptWnd)
function npcd_dashboard_tab:__init() super()
    xml:ParseFile("npcd_pda_dashboard.xml")
	self:InitControls()
end

-- Initialise the interface.
function npcd_dashboard_tab:InitControls()
    Printer:Debug(LOG.INFO, CAT.UI, "Initialising NPCD PDA Dashboard UI")
	self:SetWndRect(Frect():set(0, 0, 1024, 768))
	

    -- Apps Bar
    self:InitAppsBar()
    xml:InitStatic("left_side", self)

    -- App Panel
    self:InitHomePanel()
    self:InitNPCSPanel()
    self:InitPerksPanel()
    self:InitDeckPanel()
    self:ActivateAppPanel(APP.HOME)

    xml:InitStatic("right_side", self)
    -- Footer
    self.footer = xml:InitStatic("footer", self)

end

function npcd_dashboard_tab:InitAppsBar()

    self.apps_bar = xml:InitStatic("apps_bar", self)
    xml:InitStatic("apps_bar:background", self.apps_bar)

    -- FX: Scanlines on Apps Bar
    local scanlines = npcd_ui_fx.get_fx_config(npcd_ui_fx.FX.SCANLINES)
    scanlines.dialog = self.apps_bar
    scanlines.start =  0
    scanlines.speed = 0.04
    scanlines.margin_v = 20
    scanlines.margin_h = 30
    scanlines.orientation = 1
    npcd_ui_fx.add_fx(scanlines)
    self.apps_bar_scanline = scanlines

    -- FX: Flickering on Apps Bar
    local flickering = npcd_ui_fx.get_fx_config(npcd_ui_fx.FX.FLICKERING)
    flickering.dialog = self.apps_bar
    flickering.flickering_duration = time_global() + math.random(10, 50) * 5 -- in ms
    npcd_ui_fx.add_fx(flickering)
    self.apps_bar_flickering = flickering

    self.app = {}
    self.app[APP.NPCS] = {}
    self.app[APP.NPCS].tab = xml:InitStatic("apps_bar:npcs", self.apps_bar)
    xml:InitStatic("apps_bar:npcs:tab_left", self.app[APP.NPCS].tab)
    self.app[APP.NPCS].button = xml:Init3tButton("apps_bar:npcs:button", self.app[APP.NPCS].tab)
    self.app[APP.NPCS].button:Enable(true)
    xml:InitStatic("apps_bar:npcs:tab_right", self.app[APP.NPCS].tab)
    self:Register(self.app[APP.NPCS].button, "app_button_" .. APP.NPCS)

    self.app[APP.PERKS] = {}
    self.app[APP.PERKS].tab = xml:InitStatic("apps_bar:perks", self.apps_bar)
    xml:InitStatic("apps_bar:perks:tab_left", self.app[APP.PERKS].tab)
    self.app[APP.PERKS].button = xml:Init3tButton("apps_bar:perks:button", self.app[APP.PERKS].tab)
    self.app[APP.PERKS].button:Enable(true)
    xml:InitStatic("apps_bar:perks:tab_right", self.app[APP.PERKS].tab)
    self:Register(self.app[APP.PERKS].button, "app_button_" .. APP.PERKS)

    self.app[APP.DECK] = {}
    self.app[APP.DECK].tab = xml:InitStatic("apps_bar:deck", self.apps_bar)
    xml:InitStatic("apps_bar:deck:tab_left", self.app[APP.DECK].tab)
    self.app[APP.DECK].button = xml:Init3tButton("apps_bar:deck:button", self.app[APP.DECK].tab)
    self.app[APP.DECK].button:Enable(true)
    xml:InitStatic("apps_bar:deck:tab_right", self.app[APP.DECK].tab)
    self:Register(self.app[APP.DECK].button, "app_button_" .. APP.DECK)

    Printer:Debug(LOG.INFO, CAT.UI, "Initialising NPCD PDA Dashboard UI Callbacks")
    self:AddCallback("app_button_" .. APP.NPCS, ui_events.BUTTON_CLICKED, self.On_NPCS_Button_Clicked, self)
    self:AddCallback("app_button_" .. APP.PERKS, ui_events.BUTTON_CLICKED, self.On_Perks_Button_Clicked, self)
    self:AddCallback("app_button_" .. APP.DECK, ui_events.BUTTON_CLICKED, self.On_Deck_Button_Clicked, self)

    npcd_ui_fx.resume_fx(self.apps_bar_scanline.id)
end

function npcd_dashboard_tab:InitHomePanel()
    -- Home Panel
    UI_APP[APP.HOME].active = false
    UI_APP[APP.HOME].dialog = xml:InitStatic("home_panel", self)
    local panel_bg = xml:InitStatic("home_panel:panel_bg", UI_APP[APP.HOME].dialog)
    xml:InitStatic("home_panel:panel_logo", panel_bg)
    UI_APP[APP.HOME].dialog:Show(false)
end

function npcd_dashboard_tab:InitNPCSPanel()
    -- NPCS Panel
    UI_APP[APP.NPCS].active = false
    UI_APP[APP.NPCS].dialog = xml:InitStatic("npcs_panel", self)

    local menu_bar = xml:InitStatic("npcs_panel:menu_bar", UI_APP[APP.NPCS].dialog)

    local panel_bg = xml:InitStatic("npcs_panel:panel_bg", UI_APP[APP.NPCS].dialog)
    xml:InitStatic("npcs_panel:v_main_separator", panel_bg)
    xml:InitStatic("npcs_panel:panel_logo", panel_bg)

    local scroller = xml:InitStatic("npcs_panel:npcs_scroller", UI_APP[APP.NPCS].dialog)
    xml:InitStatic("npcs_panel:npcs_scroller:anchor_top", scroller)
    xml:InitStatic("npcs_panel:npcs_scroller:scroller", scroller)
    xml:InitStatic("npcs_panel:npcs_scroller:anchor_bottom", scroller)

    -- FX: Scanlines on NPCS Panel
    local scanlines = npcd_ui_fx.get_fx_config(npcd_ui_fx.FX.SCANLINES)
    scanlines.dialog = scroller
    scanlines.start =  0
    scanlines.speed = 0.025
    scanlines.margin_v = 45
    scanlines.margin_h = 17
    scanlines.orientation = 1
    npcd_ui_fx.add_fx(scanlines)
    self.npcs_scroller_scanline = scanlines

    UI_APP[APP.NPCS].dialog:Show(false)
end

function npcd_dashboard_tab:InitPerksPanel()
    -- Perks Panel
    UI_APP[APP.PERKS].active = false
    UI_APP[APP.PERKS].dialog = xml:InitStatic("perks_panel", self)
    local panel_bg = xml:InitStatic("perks_panel:panel_bg", UI_APP[APP.PERKS].dialog)
    xml:InitStatic("perks_panel:panel_logo", panel_bg)
    UI_APP[APP.PERKS].dialog:Show(false)
end

function npcd_dashboard_tab:InitDeckPanel()
    -- Deck Panel
    UI_APP[APP.DECK].active = false
    UI_APP[APP.DECK].dialog = xml:InitStatic("deck_panel", self)
    local panel_bg = xml:InitStatic("deck_panel:panel_bg", UI_APP[APP.DECK].dialog)
    xml:InitStatic("deck_panel:panel_logo", panel_bg)
    UI_APP[APP.DECK].dialog:Show(false)
end

function npcd_dashboard_tab:ActivateAppPanel(app_name)
    if self.app_panel then
        self.app_panel:Show(false)
    end

    UI_APP[app_name].active = true
    self.app_panel = UI_APP[app_name].dialog
    self.app_panel:Show(true)
    self.apps_bar_scanline.direction = self.apps_bar_scanline.direction * -1

    npcd_ui_fx.resume_fx(self.apps_bar_flickering.id)
    -- stopping all panel fx on app change
    -- npcd_ui_fx.stop_fx(self.npcs_scroller_scanline.id)
end

function npcd_dashboard_tab:On_NPCS_Button_Clicked()
    Printer:Debug(LOG.INFO, CAT.UI, "NPCS Button Clicked")
    self.app[APP.NPCS].button:Enable(false)
    self.app[APP.PERKS].button:Enable(true)
    self.app[APP.DECK].button:Enable(true)
    self:ActivateAppPanel(APP.NPCS)
    npcd_ui_fx.resume_fx(self.npcs_scroller_scanline.id)
end

function npcd_dashboard_tab:On_Perks_Button_Clicked()
    Printer:Debug(LOG.INFO, CAT.UI, "PERKS Button Clicked")
    self.app[APP.NPCS].button:Enable(true)
    self.app[APP.PERKS].button:Enable(false)
    self.app[APP.DECK].button:Enable(true)
    self:ActivateAppPanel(APP.PERKS)
end

function npcd_dashboard_tab:On_Deck_Button_Clicked()
    Printer:Debug(LOG.INFO, CAT.UI, "DECK Button Clicked")
    self.app[APP.NPCS].button:Enable(true)
    self.app[APP.PERKS].button:Enable(true)
    self.app[APP.DECK].button:Enable(false)
    self:ActivateAppPanel(APP.DECK)
end

function npcd_dashboard_tab:EnableAppButtons(enable)
    for app_name, app in pairs(self.app) do
        app.button:Enable(enable)
    end
end

function npcd_dashboard_tab:Update()
    CUIScriptWnd.Update(self)
    -- Update the dashboard contents here if needed.
end

function on_key_release(key)
    if key == DIK_keys.DIK_J then
        local pda_menu = ActorMenu.get_pda_menu()
        local pda3d = get_console_cmd(1,"g_3d_pda")
        if not (pda_menu:IsShown()) and db.actor:item_in_slot(8) then
            if (pda3d) then
                db.actor:activate_slot(8)
            else
                pda_menu:ShowDialog(true)
            end
            
            pda_menu:SetActiveSubdialog("eptNPCD")
        elseif (pda_menu:IsShown()) then
            if (pda3d) then
                db.actor:activate_slot(0)
            else
                pda_menu:HideDialog()
            end
        end
    end
end

function on_game_start()
    if mac_mcm then
        mac_mcm.add_app("npcd", {
            name = "pda_btn_npcd",
            texture = "pda_npcd_app",
            tab = "eptNPCD",
            func = npcd_pda_dashboard.get_ui
        })
    end
	RegisterScriptCallback("on_key_release",on_key_release)
end
