local npcdu = npcd_utils

function get_printer()
	if not Printer then
		Printer = npcd_logging.get_printer("npcd_pda_dashboard")
	end 
	LOG = Printer:GetLogTypes()
	CAT = Printer:GetLogCategories()
end
RegisterScriptCallback("npcd_on_log_update", get_printer)


if not mac_mcm then
    local original_set_active_subdialog = pda.set_active_subdialog
    pda.set_active_subdialog = function (section)
        if (section == "eptNPCD") then
            return get_ui()
        else
            return original_set_active_subdialog(section)
        end
    end
end

local xml = CScriptXmlInit()

local SINGLETON = nil
function get_ui()
	SINGLETON = SINGLETON or npcd_dashboard_tab()
	return SINGLETON
end


-- APP
local APP = {
    NPCS = "npcs",
    PERKS = "perks",
    DECK = "deck"
}

local UI_APP = {}
UI_APP = {
    [APP.NPCS] = {
        active = nil,
        dialog = nil,
    },
    [APP.PERKS] = {
        active = nil,
        dialog = nil,
    },
    [APP.DECK] = {
        active = nil,
        dialog = nil,
    }
}
-- NPCS menu
local UI_MENU = {}
UI_MENU["npcs"] = {
    SQUAD = {},
    FAVORITES = {},
    RECRUITABLE = {},
    ALL = {},
    DEAD = {},
}

-- Perks menu
UI_MENU["perks"] = {
    DISCOVERED = {},
    ALL = {},
    LEARNED = {}
}

-- Deck menu
UI_MENU["deck"] = {
    PERKS = {},
    FEATS = {},
    EFFECTS = {}
}

-- Constructor.
class "npcd_dashboard_tab" (CUIScriptWnd)
function npcd_dashboard_tab:__init() super()
    xml:ParseFile("npcd_pda_dashboard.xml")
	self:InitControls()
    self:InitCallbacks()
end

-- Initialise the interface.
function npcd_dashboard_tab:InitControls()
    Printer:Debug(LOG.INFO, CAT.UI, "Initialising NPCD PDA Dashboard UI")
	self:SetWndRect(Frect():set(0, 0, 1024, 768))
	
	-- NPCD window.
	self.apps_bar = xml:InitStatic("apps_bar", self)
    xml:InitStatic("apps_bar:background", self.apps_bar)
	self.main = xml:InitStatic("main", self)
    self.vsep_main = xml:InitStatic("v_main_separator", self)
    self.sidebar = xml:InitStatic("sidebar", self)
    self.footer = xml:InitStatic("footer", self)

    -- APP

    self.app = {}
    self.app[APP.NPCS] = {}
    self.app[APP.NPCS].tab = xml:InitStatic("apps_bar:npcs", self.apps_bar)
    xml:InitStatic("apps_bar:npcs:tab_left", self.app[APP.NPCS].tab)
    self.app[APP.NPCS].button = xml:Init3tButton("apps_bar:npcs:button", self.app[APP.NPCS].tab)
    self.app[APP.NPCS].button:Enable(true)
    xml:InitStatic("apps_bar:npcs:tab_right", self.app[APP.NPCS].tab)
    self:Register(self.app[APP.NPCS].button, "app_button_" .. APP.NPCS)

    self.app[APP.PERKS] = {}
    self.app[APP.PERKS].tab = xml:InitStatic("apps_bar:perks", self.apps_bar)
    xml:InitStatic("apps_bar:perks:tab_left", self.app[APP.PERKS].tab)
    self.app[APP.PERKS].button = xml:Init3tButton("apps_bar:perks:button", self.app[APP.PERKS].tab)
    self.app[APP.PERKS].button:Enable(true)
    xml:InitStatic("apps_bar:perks:tab_right", self.app[APP.PERKS].tab)
    self:Register(self.app[APP.PERKS].button, "app_button_" .. APP.PERKS)

    self.app[APP.DECK] = {}
    self.app[APP.DECK].tab = xml:InitStatic("apps_bar:deck", self.apps_bar)
    xml:InitStatic("apps_bar:deck:tab_left", self.app[APP.DECK].tab)
    self.app[APP.DECK].button = xml:Init3tButton("apps_bar:deck:button", self.app[APP.DECK].tab)
    self.app[APP.DECK].button:Enable(true)
    xml:InitStatic("apps_bar:deck:tab_right", self.app[APP.DECK].tab)
    self:Register(self.app[APP.DECK].button, "app_button_" .. APP.DECK)

end

function npcd_dashboard_tab:InitCallbacks()
    Printer:Debug(LOG.INFO, CAT.UI, "Initialising NPCD PDA Dashboard UI Callbacks")
    self:AddCallback("app_button_" .. APP.NPCS, ui_events.BUTTON_CLICKED, self.On_NPCS_Button_Clicked, self)
    self:AddCallback("app_button_" .. APP.PERKS, ui_events.BUTTON_CLICKED, self.On_Perks_Button_Clicked, self)
    self:AddCallback("app_button_" .. APP.DECK, ui_events.BUTTON_CLICKED, self.On_Deck_Button_Clicked, self)
end

function npcd_dashboard_tab:On_NPCS_Button_Clicked()
    Printer:Debug(LOG.INFO, CAT.UI, "NPCS Button Clicked")
    self.app[APP.NPCS].button:Enable(false)
    self.app[APP.PERKS].button:Enable(true)
    self.app[APP.DECK].button:Enable(true)
end

function npcd_dashboard_tab:On_Perks_Button_Clicked()
    Printer:Debug(LOG.INFO, CAT.UI, "PERKS Button Clicked")
    self.app[APP.NPCS].button:Enable(true)
    self.app[APP.PERKS].button:Enable(false)
    self.app[APP.DECK].button:Enable(true)
end

function npcd_dashboard_tab:On_Deck_Button_Clicked()
    Printer:Debug(LOG.INFO, CAT.UI, "DECK Button Clicked")
    self.app[APP.NPCS].button:Enable(true)
    self.app[APP.PERKS].button:Enable(true)
    self.app[APP.DECK].button:Enable(false)
end

function npcd_dashboard_tab:EnableAppButtons(enable)
    for app_name, app in pairs(self.app) do
        app.button:Enable(enable)
    end
end

function npcd_dashboard_tab:Update()
    CUIScriptWnd.Update(self)
    -- Update the dashboard contents here if needed.
end

function on_key_release(key)
    if key == DIK_keys.DIK_J then
        local pda_menu = ActorMenu.get_pda_menu()
        local pda3d = get_console_cmd(1,"g_3d_pda")
        if not (pda_menu:IsShown()) and db.actor:item_in_slot(8) then
            if (pda3d) then
                db.actor:activate_slot(8)
            else
                pda_menu:ShowDialog(true)
            end
            
            pda_menu:SetActiveSubdialog("eptNPCD")
        elseif (pda_menu:IsShown()) then
            if (pda3d) then
                db.actor:activate_slot(0)
            else
                pda_menu:HideDialog()
            end
        end
    end
end

function on_game_start()
    if mac_mcm then
        mac_mcm.add_app("npcd", {
            name = "pda_btn_npcd",
            texture = "pda_npcd_app",
            tab = "eptNPCD",
            func = npcd_pda_dashboard.get_ui
        })
    end
	RegisterScriptCallback("on_key_release",on_key_release)
end
